language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bigdatawonders/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bigdatawonders/docker-react npm run test -- --coverage